# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tox:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
      - name: Install Tox
        run: pip install tox
      - name: Upgrade setuptools
        run: pip install -U setuptools
      - name: Run Tox
        run: tox

  run-hadolint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run hadolint for GraphQL API
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile.graphql-api
      - name: Run hadolint for Storage
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile.storage

  build-docker-images:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build GraphQL API image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.graphql-api
      - name: Build Storage image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.storage
